### endpoint /auth/
### Авторизация
POST http://127.0.0.1:8000/api/auth/token/login/
Content-Type: application/json

{
    "email": "admin499@adm.ru",
    "password": "2d13ed2d123qd23d1232e"
}

###


# @token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyOWY0ZTRjODRkNzViMGJmNDQzZjUwNyIsInVzZXJuYW1lIjoiYWRtaW4iLCJleHAiOjE2NTk3OTIxNDIsImlhdCI6MTY1NDYwODE0Mn0.cpKJTriqnxpzH-_fert-NHSIFjzi_6cOU01ZPQY0jNE
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyOWU5OWY3MDhmMjU5OGQ5Nzc5ZmYyNiIsInVzZXJuYW1lIjoiYWRtaW4iLCJleHAiOjE2NjA1NDgzMDUsImlhdCI6MTY1NTM2NDMwNX0.0PwI4eG1FDul2qKfPWe9mEZUg3YJpxZePWbLKCTWhQU

###

POST http://127.0.0.1:8000/api/auth/token/logout/
Authorization: Token {{token}}

###










### endpoint /users/



POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "admin",
    "about": "admin ruled",
    "avatar": "https://i.pinimg.com/originals/4f/53/d1/4f53d166f64d6f87fc737845b91db497.jpg"
}

###

POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "user",
    "about": "admin ruled",
    "avatar": "https://i.pinimg.com/originals/4f/53/d1/4f53d166f64d6f87fc737845b91db497.jpg"
}

###

GET http://localhost:3000/users
Content-Type: application/json


###

GET http://localhost:3000/users/632c52e10053f19ca8e6dd8b
Content-Type: application/json

###

GET http://localhost:3000/users/632c58ab0053f19ca8e6dd8d
Content-Type: application/json

###

POST http://localhost:3000/cards
Content-Type: application/json

{
    "name": "beautiful place",
    "link": "https://bugaga.ru/uploads/posts/2013-12/1386102178_voshititelnye-mesta-12.jpg"
}

###

GET http://localhost:3000/cards
Content-Type: application/json

###

PUT http://localhost:3000/cards/632c760a6057645af241bb9b/likes
Content-Type: application/json

###

DELETE http://localhost:3000/cards/632c760a6057645af241bb9b/likes
Content-Type: application/json

###

